name: Build Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'   # ใช้ได้ หรือจะอัปเป็นใหม่กว่านี้ก็ได้
          channel: 'stable'
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Windows App (Release)
        run: flutter build windows --release

      # 👉 ค้นหาโฟลเดอร์ Release แบบยืดหยุ่น (x64/arm64 และ legacy path)
      - name: Locate Release folder
        id: locate
        shell: pwsh
        run: |
          $candidates = @(
            "build\windows\x64\runner\Release",
            "build\windows\arm64\runner\Release",
            "build\windows\runner\Release"
          )
          foreach ($p in $candidates) {
            if (Test-Path $p) {
              Write-Host "Found: $p"
              "release_dir=$p" >> $env:GITHUB_OUTPUT
              exit 0
            }
          }
          Write-Host "Release folder not found. Current build\windows tree:"
          Get-ChildItem -Recurse -Force build\windows | Select-Object FullName
          Write-Error "No Release directory found in expected locations."
          exit 1

      - name: List files in Release
        run: |
          dir "${{ steps.locate.outputs.release_dir }}"

      - name: Create ZIP artifact
        shell: pwsh
        run: |
          $source = "${{ steps.locate.outputs.release_dir }}"
          $zip = "flutter_smartbed_windows.zip"
          if (Test-Path $source) {
            Write-Host "Creating ZIP from: $source"
            if (Test-Path $zip) { Remove-Item $zip -Force }
            Compress-Archive -Path "$source\*" -DestinationPath $zip -Force
          } else {
            Write-Error "Build directory not found: $source"
            exit 1
          }

      # ออกรุ่นเฉพาะตอน push tag (ตัวอย่าง: v1.0.0)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: flutter_smartbed_windows.zip
          name: Flutter Smart Bed v${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: flutter_smartbed_windows.zip
          retention-days: 90
